version: "3.7"
services:
<<<<<<< HEAD
  api: 
    build: 
      context: ./
      dockerfile: containers/api-Dockerfile
    # environment:
    #   - PORT=8080
    ports:
      - "8000:8000"


  redis:
    image: redis
    ports:
      - "6379:6379"

=======
  redis:
    image: redis
    ports:
      - "6380:6380"
>>>>>>> 2abe167 (fast api)
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ontobridge
<<<<<<< HEAD
=======
      PGDATA: /data/postgres
>>>>>>> 2abe167 (fast api)
    volumes:
      - postgres:/data/postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
<<<<<<< HEAD
      - "5050:80"
    depends_on:
      - postgres

  flask-app:
    build:
      context: ../embeddings
      dockerfile: Dockerfile
    image: embedding:latest
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis

=======
      - "5051:80"
    depends_on:
      - postgres

>>>>>>> 2abe167 (fast api)
volumes:
  postgres:
