version: "3.7"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ontobridge
    volumes:
      - postgres:/data/postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  flask-app:
    build:
      context: ../embeddings
      dockerfile: Dockerfile
    image: embedding:latest
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis

volumes:
  postgres:
