
services:
  app:
    build: .
    image: ariane:latest
    # command: ls -la app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    env_file:
      - .env
    # volumes:
    #   - .:/app
