query VECEscoJob($queryVector: [Float]) {
  esco(queryVector: $queryVector) {
    Occupation {
      id
      type
      prefLabel {
        value
      }
      _met {
        score
      }
    }
  }
}