query VECRomeJob($queryVector: [Float]) {
  rome(queryVector: $queryVector) {
    employment {
      Position {
        id
        type
        prefLabel {
          value
        }  
      }
    }
  }
}